import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
    pageContent: {
      alignContent: 'center',
      alignItems: 'center',
      display: 'flex',
      flexDirection: 'column',
      minHeight: '100vh',
      padding: theme.spacing(2, 4),
    },
    root: {
      fontFamily: '"Montserrat", sans-serif',
      fontSize: 16,
      '--flamingo-500': '#f15a24',
      '--grey-050': '#efefef',
      '--grey-100': '#d9d9da',
      '--grey-200': '#c3c3c4',
      '--grey-300': '#adadaf',
      '--grey-400': '#979799',
      '--grey-500': '#818284',
      '--grey-600': '#6b6c6e',
      '--grey-700': '#555659',
      '--grey-800': '#3f4043',
      '--grey-900': '#292a2e',
      '--text-color': 'var(--grey-900)',
      '--background-color': '#fff',
      '--primary': 'black',
      '--secondary': '#cdcdcd',
      '--accent': '#323232',
      background: 'var(--background-color)',
      color: 'var(--text-color)',
      boxSizing: 'border-box',
    },
    htmlBody: {
      margin: 0,
      width: '100vw',
    },
    p: {
      lineHeight: '22px',
      color: 'var(--grey-700)',
      fontSize: '1rem',
      margin: '1rem 0',
    },
    input: {
      marginBottom: '1rem',
      padding: '0.4rem 1rem',
      borderRadius: 4,
      border: `2px var(--grey-100) solid`,
      width: 'auto',
      backgroundColor: 'var(--background-color)',
      lineHeight: '1.25rem',
      letterSpacing: '0.005em',
    },
    erroredInput: {
      border: `double 2px var(--flamingo-500)`,
    },
    erroredInputPlaceholder: {
      color: 'var(--flamingo-500)',
    },
    h1: {
      marginTop: 0,
      fontSize: '1.8rem',
      margin: 'auto',
      [theme.breakpoints.up('1024')]: {
        margin: 'inherit',
      },
    },
    h1H6: {
      margin: '0 0 1rem',
    },
    button: {
      border: `1px solid black`,
      background: 'var(--background-color)',
      display: 'flex',
      width: '100%',
      textAlign: 'center',
      justifyContent: 'center',
      marginBottom: '1rem',
      padding: '0.6rem 1rem',
      borderRadius: 4,
      lineHeight: '1.25rem',
      letterSpacing: '0.005em',
      '&:hover, &:focus, a:focus': {
        opacity: 0.9,
        boxShadow: `0 0 0 2px #ffffff, 0 0 3px 5px #29abe2`,
        outline: `2px dotted transparent`,
        outlineOffset: 2,
      },
    },
    img: {
      minWidth: 500,
      width: '50vw',
      maxWidth: 800,
      display: 'block',
      margin: 'auto',
    },
    ul: {
      width: '100%',
      padding: 0,
    },
    formLabel: {
      display: 'flex',
    },
    form: {
      marginBottom: '2rem',
      flexDirection: 'column',
    },
    primaryButton: {
      backgroundColor: 'var(--primary)',
      color: 'var(--background-color)',
      border: 'none',
    },
    linkStyleButton: {
      cursor: 'pointer',
      display: 'inline',
      border: 'none',
      padding: 0,
      margin: 0,
      width: 'auto',
    },
    label: {
      fontSize: '1rem',
      fontWeight: 500,
      flexDirection: 'column',
      marginBottom: '0.5rem',
    },
    mainBefore: {
      content: '""',
      display: 'block',
      flexGrow: 1,
      height: 24,
    },
    main: {
      height: '100vh',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
    },
    mainAfter: {
      content: '""',
      display: 'block',
      flexGrow: 2,
      height: 24,
    },
    container: {
      padding: '3.5rem 2.5rem 2rem 2.5rem',
      maxWidth: 365,
      minWidth: 300,
      flex: '0 0 auto',
      display: 'flex',
      flexDirection: 'column',
      [theme.breakpoints.up('512')]: {
        border: `3px #B5C0D0 solid`,
        borderRadius: 10,
      },
    },
    logoutButton: {
      display: 'flex',
      padding: 8,
      margin: '1rem 1rem 1rem auto',
      fontSize: '0.8rem',
      width: 'auto',
    },
    highlightBox: {
      backgroundColor: 'var(--grey-100)',
      padding: '0.7rem 0rem',
      textAlign: 'center',
      borderRadius: 4,
      marginBottom: '1rem',
      overflowWrap: 'break-word',
      fontSize: '1.5rem',
      fontWeight: 500,
    },
    warningBox: {
      border: `1px var(--grey-200) solid`,
      borderRadius: 4,
      padding: '1rem 2rem',
    },
    hr: {
      marginBottom: '1rem',
      width: '100%',
      borderTop: `1px solid var(--grey-400)`,
    },
    icLogo: {
      width: '80%',
      alignSelf: 'center',
      marginTop: '-3rem',
    },
    aboutLink: {
      textDecoration: 'none',
      color: 'var(--grey-600)',
      marginTop: '1rem',
      fontSize: '0.875rem',
    },
    deviceItem: {
      display: 'flex',
      width: '100%',
    },
    deviceItemAlias: {
      border: `1px solid var(--grey-200)`,
      borderRadius: 2,
      height: 40,
      display: 'flex',
      alignItems: 'center',
      flex: '1 1 auto',
      marginRight: '0.5rem',
      paddingLeft: '1rem',
    },
    deviceItemRemove: {
      borderRadius: 2,
      padding: 0,
      width: 40,
      height: 40,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    header: {
      position: 'absolute',
      top: '1rem',
      left: 0,
      width: '100vw',
      display: 'flex',
      justifyContent: 'center',
    },
    toast: {
      fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji',
      tabSize: 4,
      lineHeight: 'inherit',
      border: '0 solid #e5e7eb',
      boxSizing: 'border-box',
      display: 'flex',
      width: '100%',
      maxWidth: '20rem',
      alignItems: 'center',
      borderRadius: '0.5rem',
      padding: '1rem',
      boxShadow: 'var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)',
      backgroundColor: 'rgb(31 41 55 / var(--tw-bg-opacity))',
      color: 'white',
    },
    toastSpan: {
      fontFamily: 'inherit',
      color: 'inherit',
    },
    closeButton: {
      fontFamily: 'inherit',
      fontSize: '100%',
      fontWeight: 'inherit',
      lineHeight: 'inherit',
      textTransform: 'none',
      cursor: 'pointer',
      appearance: 'button',
      backgroundImage: 'none',
      marginRight: '-0.375rem',
      marginBottom: '-0.375rem',
      marginTop: '-0.375rem',
      marginLeft: 'auto',
      display: 'inline-flex',
      height: '2rem',
      width: '2rem',
      borderRadius: '0.5rem',
      padding: '0.375rem',
      backgroundColor: 'rgb(31 41 55 / var(--tw-bg-opacity))',
      color: 'white',
    },
    hidden: {
      display: 'none',
      visibility: 'hidden',
    },
  }));